server:
  port: 8081
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active:
      - "qa"

build:
  version: "1.0.0"

accounts:
  message: "Hello from Accounts"
  contactDetails:
    phone: "+1-123-456-7890"
    email: "accounts@example.com"
  onCallSupport:
    - "+1-987-654-3210"
    - "+1-555-555-5555"